version: '3.8'
services:

  db:
    image: postgres:16
    container_name: postgres_liquibase
    environment:
      POSTGRES_DB: liquibase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nata1234.
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase_runner
    depends_on:
      - db
    volumes:
      - ./:/liquibase/project              # 👈 MONTA TODO el proyecto
      - ./liquibase:/liquibase/config      # 👈 properties + driver
    working_dir: /liquibase/project
    command: >
      sh -c "sleep 10 && liquibase --classpath=/liquibase/config/driver/postgresql-42.7.9.jar --defaultsFile=/liquibase/config/liquibase.properties update"

volumes:
  pgdata: